### ISSUE TITLE
Credentials not set

### ISSUE THREAD

**Issue by JFaeth** [FlorianZ/hadashboard#48]
I am really honestly a noob to all this. I have tried doing all the steps using FlorianZ's code only to have a failure with my gem file being corrupt. Got past that by using bmillers fork of the project. Now I have an app that when I navigate to the "http://your-app-name.herokuapp.com" link I created, I get a white screen that just says "Credentials not set" in the top left hand corner. I have tried many different ways of entering the config variables assuming that was the issue only to return the same issue. I did notice when I run the config:set command I get this output:

 \DASHING_AUTH_TOKEN, \DASHING_URI, \HEROKU_OAUTH_EMAIL, \HEROKU_OAUTH_ID, \HEROKU_OAUTH_SECRET, \SESSION_SECRET, \ST_CLIENT_ID, \ST_CLIENT_SECRET and restarting fathomless-taiga-45030... !
!     Name is ivalid

Not sure if that last bit is a problem or if that looks right.
Also when I go to install the heroku-oauth: 

heroku-oauth
Installing plugin https://github.com/heroku/heroku-oauth...module.js:471
    throw err;
    ^

Error: Cannot find module 'https://github.com/heroku/heroku-oauth'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Jeremy\AppData\Local\heroku\tmp\heroku-script-209067047:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
 !
 !    Error installing plugin https://github.com/heroku/heroku-oauth

Found if i navigate to the actual link it redirects me to https://github.com/heroku/heroku-cli-oauth in the browser. Used that link in place of the other and I get: 

heroku plugins:install heroku-cli-oauth
 !    Not installing heroku-cli-oauth because it is already installed as a core plugin.

So I assume I can skip that step and move to the creation of clients, which always seems to work fine.

I hope I dont come off as super stupid and I am getting my info across coherently. Like I said I am a super noob just trying to learn this stuff on my own in my free time. I appreciate all the help you guys give and these great apps you guys write. Hopefully one day I will be able to write something as well as you guys do!

**Comment by bmmiller** [comment]
It doesn't sound like any of your config values are being saved.

What happens if you just type 'heroku config' ? Not with ':set'

If everything is stored correctly, each item should have an actual value associated with it.
