### ISSUE TITLE
Error installing plugin

### ISSUE THREAD

**Issue by Tokn59** [FlorianZ/hadashboard#51]
Hello when I try to install the plugin I get the following error message 👍 

Installing plugin https://github.com/heroku/heroku-cli-oauth...module.js:472
    throw err;
    ^

Error: Cannot find module 'https://github.com/heroku/heroku-cli-oauth'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\TonyKnors\AppData\Local\heroku\tmp\heroku-script-505313519:2:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
 !
 !    Error installing plugin https://github.com/heroku/heroku-cli-oauth

Any idea what is going wrong ?

Thanks for your support !

Tony

**Comment by bmmiller** [comment]
Are you using the Heroku CLI or just a terminal or command prompt manually pushing to your Heroku repo?  The Heroku CLI comes with this plugin built in.

**Comment by kerednai** [comment]
Had the same problem. The heroku-cli-oauth plugin is now included in the base cli so you should be able to skip this step.

**Comment by bmmiller** [comment]
Thanks @kerednai, updated the readme and am closing this.
